### PR TITLE
update rally scenarios

### PR DESCRIPTION
**Pull request by kevkha**
update to rally 0.3.1 scenarios

### CODE REVIEW

**Comment by briandowns** [comment]
Give me half of today to get some clean up work done on this repo and then have at it again.  Thanks.

**Comment by kevkha** [comment]
Sounds good. Will update readme later. Thanks.

**Comment by briandowns** [comment]
Project has been completely restructured and refactored.  Please make sure you do a fetch before doing any further changes.  This is still far from working so a lot of work still needs to go into it.  That being the case and so there's no toe stepping, let's start using the issues section to add the work we think needs to get done and have branches correlating to those issues.

**Comment by kevkha** [comment]
Awesome! Thanks so much for your efforts, Brian. Happy racing with rally!

**Pull request merged**
