### PR TITLE
Use rally 0.3.1 scenarios

### PR DESCRIPTION
**Pull request by kevkha**

### CODE REVIEW

**Comment by briandowns** [comment]
Let's get one PR at a time going before we start doing more.  Both have merge conflicts that need to be resolved before anyting is merged to master.  That should be a foscus before anything else.

**Comment by kevkha** [comment]
Can you revert your changes earlier on master? That would help the conflicts.

**Comment by briandowns** [comment]
It would be 1000 times simpler if you just pull the changes and merge them to your branch. That's what you would have to do when I Mergen other branches to master that you don't currently have

**Comment by kevkha** [comment]
My remote origin/master is from kevkha/raceway not from yours so when I do a pull it does not help. I will probably delete mine and fork from yours again.

**Comment by briandowns** [comment]
Add mine as a remote and do a get fetch. It's the same procedure you would do as maintaining a fork in keeping up-to-date from the original.

**Comment by briandowns** [comment]
http://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository

**Comment by kevkha** [comment]
Thanks I just got it working by using `git remote add`.

**Pull request closed without merging**
